import openai
import os



class chat_api:
    """
    This class represents the brain API for interacting with the GPT-3.5-turbo model.
    """

    def __init__(self,api_key):
        """
        Initializes the brain API with the OpenAI API key.
        """
        self.api_key = api_key
        self.model = "gpt-3.5-turbo-0613"
        openai.api_key = self.api_key
        
    def get_completion_for_message(self, message, temperature=0):
        """
        Generates a completion for a given message using the GPT-3.5-turbo model.

        Args:
            message (list): List of messages representing the conversation history.
            temperature (float): Control the randomness of the output.

        Returns:
            str: The completion generated by the model.
            int: The number of tokens used by the completion.
        """
        completion = openai.ChatCompletion.create(
            model=self.model,
            messages=message,
            temperature=temperature
        )
        return completion.choices[0].message['content'], completion['usage']['prompt_tokens']
    
    def get_completion(self, message_history, message='', update_history=False, temperature=0):
        """
        Generates a completion for the conversation history.

        Args:
            message_history (message_history): The conversation history.
            message (str): The user's message to be added to the history.
            update_history (bool): Flag to update the conversation history.
            temperature (float): Control the randomness of the output.

        Returns:
            str: The completion generated by the model.
            int: The number of tokens used by the completion.
        """
        if message == '':
            completion_output = self.get_completion_for_message(message_history.messages, temperature)
            if update_history:
                message_history.add_assistant(completion_output[0])
                message_history.tokens = completion_output[1]
                return message_history.get_last_message()['content'], message_history.tokens
            else:
                return completion_output
        else:
            if update_history:
                message_history.add_user(message)
                completion_output = self.get_completion_for_message(message_history.messages, temperature)
                message_history.add_assistant(completion_output[0])
                message_history.tokens = completion_output[1]
                return message_history.get_last_message()['content'], message_history.tokens
            else:
                temporary_message = message_history.messages.copy()
                temporary_message.append({"role": "user", "content": message})
                completion_output = self.get_completion_for_message(temporary_message, temperature)
                return completion_output
    
    def converse(self, message_history, update_history=False, temperature=0):
        """
        Starts a conversation with the model.

        Args:
            message_history (message_history): The conversation history.
            update_history (bool): Flag to update the conversation history.
            temperature (float): Control the randomness of the output.
        """
        print(self.get_completion(message_history=message_history, update_history=update_history, temperature=temperature))
        while True:
            user_input = input()
            if user_input == '\\break':
                return message_history
            print(self.get_completion(message_history=message_history, message=user_input, update_history=update_history, temperature=temperature))

class message_history_base:
    """
    This class represents the message history for a conversation.
    """

    def __init__(self):
       
        #Initializes the message history.
        self.messages = []
        self.tokens = 0
    
    def add(self, role, content):
        """
        Adds a message to the message history.

        Args:
            role (str): The role of the message (user, assistant, etc.).
            content (str): The content of the message.
        """
        self.messages.append({"role": role, "content": content})
    
    def add_user(self, content):
        """
        Adds a user message to the message history.

        Args:
            content (str): The content of the user message.
        """
        self.messages.append({"role": "user", "content": content})
    
    def add_assistant(self, content):
        """
        Adds an assistant message to the message history.

        Args:
            content (str): The content of the assistant message.
        """
        self.messages.append({"role": "assistant", "content": content})
    
    def add_system(self, content):
        """
        Adds a system message to the message history.

        Args:
            content (str): The content of the system message.
        """
        self.messages.append({"role": "system", "content": content})
    
    def append(self, content_list):
        """
        Appends a list of messages to the message history.

        Args:
            content_list (list): List of messages to be appended.
        """
        self.messages.extend(content_list)
    
    def get_last_message(self):
        """
        Returns the last message in the message history.

        Returns:
            dict: The last message in the message history.
        """
        return self.messages[-1]
    
class message(message_history_base):
    def load_persona(self):
        summary = os.environ.get('SUMMARY')
        self.add_system(f"Hey this is the summary of the person {summary} Now pretend that you are that person")